"""add_project_application_type

Revision ID: 2f816d647e4a
Revises: 3e29ca94bbb8
Create Date: 2026-06-17 01:18:24.066668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f816d647e4a'
down_revision: Union[str, None] = '3e29ca94bbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('application_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'application_type')
    # ### end Alembic commands ###
