"""add_task_id_to_comments

Revision ID: 3e29ca94bbb8
Revises: 8eaaa7a1a3f7
Create Date: 2026-06-17 00:30:47.634742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e29ca94bbb8'
down_revision: Union[str, None] = '8eaaa7a1a3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('task_id', sa.UUID(), nullable=True))
    op.alter_column('comments', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.alter_column('comments', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('comments', 'task_id')
    # ### end Alembic commands ###
