"""make_email_nullable_and_add_mobile_number

Revision ID: 4b4da0e325a7
Revises: 4c10fe5bd9d5
Create Date: 2026-06-20 01:25:37.893457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4da0e325a7'
down_revision: Union[str, None] = '4c10fe5bd9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('mobile_number', sa.String(length=50), nullable=True))
    op.alter_column('otp_verifications', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_otp_verifications_mobile_number'), 'otp_verifications', ['mobile_number'], unique=False)
    op.add_column('users', sa.Column('mobile_number', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'mobile_number')
    op.drop_index(op.f('ix_otp_verifications_mobile_number'), table_name='otp_verifications')
    op.alter_column('otp_verifications', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('otp_verifications', 'mobile_number')
    # ### end Alembic commands ###
