"""add_priority_to_projects

Revision ID: 4c10fe5bd9d5
Revises: b2c3d4e5f6a7
Create Date: 2026-06-20 00:36:30.276241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c10fe5bd9d5'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('priority', sa.String(length=100), nullable=True))
    op.drop_column('projects', 'application_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('projects', 'priority')
    # ### end Alembic commands ###
