"""remove_mobile_number

Revision ID: 7375cb0d1e9d
Revises: 4b4da0e325a7
Create Date: 2026-06-20 01:38:48.699626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7375cb0d1e9d'
down_revision: Union[str, None] = '4b4da0e325a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete dependent rows where users have email IS NULL
    op.execute("DELETE FROM task_assignees WHERE user_id IN (SELECT id FROM users WHERE email IS NULL)")
    op.execute("DELETE FROM workspace_members WHERE user_id IN (SELECT id FROM users WHERE email IS NULL)")
    op.execute("DELETE FROM comments WHERE author_id IN (SELECT id FROM users WHERE email IS NULL)")
    op.execute("DELETE FROM workspaces WHERE owner_id IN (SELECT id FROM users WHERE email IS NULL)")
    op.execute("DELETE FROM users WHERE email IS NULL")
    op.execute("DELETE FROM otp_verifications WHERE email IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_column('users', 'mobile_number')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_otp_verifications_mobile_number'), table_name='otp_verifications')
    op.drop_column('otp_verifications', 'mobile_number')
    op.alter_column('otp_verifications', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('mobile_number', sa.String(length=50), nullable=True))
    op.alter_column('otp_verifications', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_otp_verifications_mobile_number'), 'otp_verifications', ['mobile_number'], unique=False)
    op.add_column('users', sa.Column('mobile_number', sa.String(length=50), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###
