"""support_project_status_multiple_tags_project_comments

Revision ID: 8eaaa7a1a3f7
Revises: 006
Create Date: 2026-06-16 23:56:07.997697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaaa7a1a3f7'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tags',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    op.create_table('task_tags',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id')
    )
    
    op.add_column('comments', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.Enum('todo', 'in_progress', 'in_review', 'done', name='task_status'), nullable=False, server_default='todo'))

    # Data migration
    op.execute("INSERT INTO project_tags (project_id, tag_id) SELECT id, tag_id FROM projects WHERE tag_id IS NOT NULL ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO task_tags (task_id, tag_id) SELECT id, tag_id FROM tasks WHERE tag_id IS NOT NULL ON CONFLICT DO NOTHING")
    op.execute("UPDATE comments SET project_id = tasks.project_id FROM tasks WHERE comments.task_id = tasks.id")
    op.execute("DELETE FROM comments WHERE project_id IS NULL")
    
    op.alter_column('comments', 'project_id', nullable=False)
    
    op.drop_index('ix_comments_task_id', table_name='comments')
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.drop_constraint('comments_task_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'task_id')
    
    op.drop_index('ix_projects_tag_id', table_name='projects')
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.drop_constraint('projects_tag_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'tag_id')
    
    op.drop_index('ix_tasks_tag_id', table_name='tasks')
    op.drop_constraint('fk_tasks_tag_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tasks_tag_id'), 'tasks', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tasks_tag_id'), 'tasks', ['tag_id'], unique=False)
    op.add_column('projects', sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_tag_id_fkey'), 'projects', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.create_index(op.f('ix_projects_tag_id'), 'projects', ['tag_id'], unique=False)
    op.drop_column('projects', 'status')
    op.add_column('comments', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_task_id_fkey'), 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    op.drop_column('comments', 'project_id')
    op.drop_table('task_tags')
    op.drop_table('project_tags')
    # ### end Alembic commands ###
